import "dotenv/config";
import { createHash } from "node:crypto";
import { getSupabase } from "../services/supabase.js";

const PROJECT_ID = process.env.FEASIBLE_PROJECT_ID?.trim() || "94dc3b92-1cae-4360-a958-917a58063309";
const documents = [
  { kind: "product_truth", title: "Feasible product truth", priority: 10, source_path: "projects/Feasible/context/feasible-mssp-partner-email-copy.md", content: `Feasible is a vulnerability management and attack surface platform for security service providers (MSSPs and VADs). One license runs 21 scanning engines covering vulnerability management (VM), external attack surface (EASM), web application testing (DAST), and credential and data leak checks. It correlates and deduplicates findings, then chains them with network reachability into feasible attack paths to the assets each client marks as critical. It is multi-tenant and runs under the partner brand: each client gets an isolated tenant (own URL, database, scan capacity) with reports in the partner's branding, all managed from one panel. Feasible is the engine under the partner's branded service. Use only capabilities stated in approved source material; omit any integration, coverage, deployment, or performance claim that is not supported.` },
  { kind: "proof_points", title: "Approved proof-point policy", priority: 20, source_path: "projects/Feasible/context/feasible-mssp-partner-email-copy.md", content: `Approved proof points, usable verbatim and never inflated: 60+ MSSPs and VADs deliver or resell the platform; the largest customer secures 100k+ live hosts. Beyond these two, use a proof point only when it appears in active project knowledge or cited evidence. Never manufacture customer names, percentages, benchmarks, deployment times, ROI figures, certifications, or integration support. A relevant operational observation is preferable to a generic unsupported claim.` },
  { kind: "icp_angle_framework", title: "MSSP partner angles", priority: 30, source_path: "projects/Feasible/context/MSSP Partner Framework.md", content: `For MSSP and VAD leaders, select one money angle grounded in their visible model: (1) productize a recurring line on a service or stack they already run, with the attack path layer sold as a subscription under their brand; (2) win more competitive bids by making the deliverable an attack-path map to critical assets instead of a flat CVE list; (3) raise delivery margin by collapsing the scanner stack into one license and moving senior hours off baseline rescanning onto billable work; (4) scale managed clients on the same headcount through multi-tenant automation. Do not assume the prospect has a problem. Frame the angle as a hypothesis tied to their visible service mix, partnerships, region, growth, or conversation history. Never use a dollar figure unless an employee count is verified.` },
  { kind: "forbidden_claims", title: "Forbidden claims", priority: 1, source_path: "projects/Feasible/context/Feasible-Full-Project-Context.md", content: `Do not claim guaranteed breach prevention, complete attack coverage, automatic remediation, compliance certification, named integrations, customer outcomes, market leadership, deployment speed, or numerical ROI unless that exact claim is present in active approved knowledge and linked evidence. Do not name colleagues, do not claim you have spoken with anyone, and do not imply an existing conversation when none exists. Do not imply private knowledge from n8n or conversation data. Never mention research tooling or internal classifications. The two approved proof points (60+ MSSPs and VADs deliver or resell the platform; the largest customer secures 100k+ live hosts) are the exception and may be stated.` },
  { kind: "messaging_style", title: "Practitioner messaging style", priority: 40, source_path: "projects/Feasible/context/feasible-practitioner-approach-canonical.md", content: `Write like a technically credible practitioner: concise, specific, calm, and curious. Plain 7th to 9th grade language, short sentences, one idea per beat, one low-friction CTA. Lead with a relevant observation phrased as a question the reader would ask themselves, not praise. No em dashes or en dashes. Do not join words with hyphens: write attack path, crown jewel asset, white label, real time. No trailing contrast ( , not X / instead of Y). No tricolons or three-item lists. No abstract metaphors (sits next to, plugs in, fits, slots in); state literally what the product does. Avoid hype, buzzwords, false familiarity, generic compliments, feature dumps, and forced urgency.` },
  { kind: "inmail_guidelines", title: "LinkedIn InMail guidelines", priority: 50, source_path: "projects/Feasible/context/feasible-mssp-partner-email-copy.md", content: `Canonical named-bullet InMail. Subject: a 3 to 4 word noun phrase, internal tone, no clickbait, no dollar sign. Body shape, in this order: (1) Hook, one or two lines: a lived practitioner question named to the contact's stack, service, or region. (2) Essence line, one sentence verbatim: Feasible runs 21 scanners for VM, EASM, DAST and leaks under one license, and ties their findings into the real attack path to each client's critical assets. (3) Proof line, verbatim: 60+ MSSPs and VADs deliver or resell the platform today. The largest customer secures 100k+ live hosts. (4) Heading: What this could mean for [Company]:. (5) Three or four named bullets: short outcome labels only, no sentence after each, parallel noun phrases, matched to the one chosen angle. Standard set: a new billed or recurring line on what they already run; less senior or analyst time on baseline scanning; faster prioritization when an alert or one CVE fires; one tenant per client under their brand, or in-region hosting when geography is the live concern. (6) One detail sentence carrying the single strongest concrete mechanism, usually the tenant, brand, or data residency detail. (7) Pilot and CTA, verbatim: We can run a 30-day pilot on a scope you pick and hand back the finished report. Open to discussing further? Keep the body self-contained, no placeholders, under 1,900 characters. Do not pretend a conversation exists. Optional variant: each bullet may expand to exactly one short sentence, never two; pick named-only or one-sentence for a given message and do not mix.` },
  { kind: "message_guidelines", title: "LinkedIn Message guidelines", priority: 50, source_path: ".cursor/rules/messaging/messaging-styles.mdc", content: `Continue the actual thread naturally. Do not add a subject, reintroduce the sender, repeat an earlier pitch, or reset the conversation. Acknowledge the latest relevant message when appropriate. Use at most one question or CTA. If the thread shows a decline, pause, or unresolved question, respect it.` },
];

const client = getSupabase();
if (!client) throw new Error("Supabase is not configured");
const project = await client.from("Projects").select("id,name").eq("id", PROJECT_ID).single();
if (project.error || project.data?.name !== "Feasible") throw new Error("Feasible project validation failed");
let upgraded = 0;
for (const d of documents) {
  const checksum = createHash("sha256").update(d.content).digest("hex");
  // Latest version (any status) and the current active checksum for this kind+title.
  const latest = await client.from("project_knowledge_documents").select("version").eq("project_id", PROJECT_ID).eq("kind", d.kind).eq("title", d.title).order("version", { ascending: false }).limit(1).maybeSingle();
  const active = await client.from("project_knowledge_documents").select("id,source_checksum").eq("project_id", PROJECT_ID).eq("kind", d.kind).eq("title", d.title).eq("status", "active").maybeSingle();
  if (active.data?.source_checksum === checksum) continue; // already current, idempotent
  // Archive any active version, then insert the new content as the next version, active.
  await client.from("project_knowledge_documents").update({ status: "archived", updated_at: new Date().toISOString() }).eq("project_id", PROJECT_ID).eq("kind", d.kind).eq("title", d.title).eq("status", "active");
  const ins = await client.from("project_knowledge_documents").insert({ project_id: PROJECT_ID, kind: d.kind, title: d.title, version: Number(latest.data?.version ?? 0) + 1, content_markdown: d.content, priority: d.priority, status: "active", source_path: d.source_path, source_checksum: checksum });
  if (ins.error) throw new Error(ins.error.message);
  upgraded += 1;
}
const configured = await client.from("project_outreach_settings").upsert({ project_id: PROJECT_ID, enabled: true, default_model: "openai/gpt-5.2", research_ttl_days: 30, contact_message_limit: 100, company_message_limit: 100, active_guideline_profile: "default", updated_at: new Date().toISOString() });
if (configured.error) throw new Error(configured.error.message);
console.log(`Feasible outreach knowledge: ${documents.length} documents checked, ${upgraded} upgraded to a new active version.`);
