<script setup lang="ts">
import { computed, h, onMounted, ref, watch } from "vue";
import { NCard, NAlert, NButton, NDataTable, NForm, NFormItem, NInput, NInputNumber, NSelect, NSpace, useMessage } from "naive-ui";
import type { DataTableColumns } from "naive-ui";
import { useProjectStore } from "../stores/project";
type Doc = { id: string; kind: string; title: string; version: number; content_markdown: string; priority: number; status: string; source_path: string | null; updated_at: string };
const store = useProjectStore(); const toast = useMessage(); const docs = ref<Doc[]>([]); const error = ref(""); const loading = ref(false); const title = ref(""); const kind = ref("product_truth"); const content = ref(""); const priority = ref(100); const sourcePath = ref("");
const kinds = ["product_truth","proof_points","icp_angle_framework","forbidden_claims","messaging_style","inmail_guidelines","message_guidelines","examples"].map((v) => ({ label: v.replace(/_/g, " "), value: v }));
async function load() { if (!store.selectedProjectId) return; loading.value = true; const r = await fetch(`/api/projects/${store.selectedProjectId}/outreach-knowledge`); const j = await r.json(); loading.value = false; if (!r.ok) error.value = j.error ?? "Could not load knowledge"; else docs.value = j.data ?? []; }
async function save() { if (!store.selectedProjectId) return; const r = await fetch(`/api/projects/${store.selectedProjectId}/outreach-knowledge`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.value, kind: kind.value, contentMarkdown: content.value, priority: priority.value, sourcePath: sourcePath.value || null }) }); const j = await r.json(); if (!r.ok) return error.value = j.error ?? "Could not save"; title.value = ""; content.value = ""; sourcePath.value = ""; toast.success("New draft version created"); await load(); }
async function activate(id: string) { if (!store.selectedProjectId) return; const r = await fetch(`/api/projects/${store.selectedProjectId}/outreach-knowledge/${id}/activate`, { method: "POST" }); const j = await r.json(); if (!r.ok) return error.value = j.error ?? "Could not activate"; toast.success("Version activated"); await load(); }
const columns = computed<DataTableColumns<Doc>>(() => [{ title: "Kind", key: "kind", render: (r) => r.kind.replace(/_/g, " ") }, { title: "Title", key: "title" }, { title: "Version", key: "version", width: 80 }, { title: "Priority", key: "priority", width: 80 }, { title: "Status", key: "status", width: 100, render: (r) => r.status }, { title: "Source", key: "source_path", ellipsis: { tooltip: true } }, { title: "", key: "actions", width: 110, render: (r) => r.status === "active" ? "Active" : h(NButton, { size: "small", onClick: () => activate(r.id) }, { default: () => "Activate" }) }]);
onMounted(load); watch(() => store.selectedProjectId, load);
</script>
<template><NSpace vertical size="large"><NCard title="Outreach Knowledge Hub"><NAlert type="info" :show-icon="false" style="margin-bottom:14px">The agent reads active versions only. Saving creates an immutable draft; activation is explicit.</NAlert><NAlert v-if="error" type="error">{{ error }}</NAlert><NDataTable :columns="columns" :data="docs" :loading="loading" :pagination="{ pageSize: 20 }"/></NCard><NCard title="Create a new version"><NForm><NFormItem label="Kind"><NSelect v-model:value="kind" :options="kinds"/></NFormItem><NFormItem label="Title"><NInput v-model:value="title" placeholder="Use the same title to create the next version"/></NFormItem><NFormItem label="Knowledge and guidelines"><NInput v-model:value="content" type="textarea" :autosize="{ minRows: 8, maxRows: 20 }"/></NFormItem><NFormItem label="Priority (lower takes precedence)"><NInputNumber v-model:value="priority" :min="1"/></NFormItem><NFormItem label="Source path"><NInput v-model:value="sourcePath"/></NFormItem><NButton type="primary" :disabled="!title.trim() || !content.trim()" @click="save">Save draft version</NButton></NForm></NCard></NSpace></template>
