import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getSupabase, getContacts } from "../services/supabase.js";

export function registerGetContactsTool(server: McpServer): void {
  server.tool(
    "get_contacts",
    "Get Contacts from Supabase (table Contacts). Filter by uuid, team_id, user_id, list_uuid, data_source_uuid, ai_agent_uuid, ai_agent_mode, ai_engagement_status_uuid, pipeline_stage_uuid, company_uuid, name, first_name, last_name, company_name, company_ln_id, position, headline, about, avatar_url, ln_member_id, ln_id, sn_id, linkedin, facebook, twitter, work_email, work_email_domain, personal_email, work_phone_number, personal_phone_number, connections_number, followers_number, primary_language, has_open_profile, has_verified_profile, has_premium, raw_address, location, status, linkedin_status, email_status, last_automation_approve_at, last_stop_on_reply_at, last_enrich_at/created_at/updated_at ranges. Supports limit, offset, ordering. Requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_ANON_KEY).",
    {
      uuid: z.string().uuid().optional().describe("Filter by contact uuid."),
      teamId: z.number().optional().describe("Filter by team_id."),
      userId: z.string().optional().describe("Filter by user_id."),
      listUuid: z.string().uuid().optional().describe("Filter by list_uuid."),
      dataSourceUuid: z.string().uuid().optional().describe("Filter by data_source_uuid."),
      aiAgentUuid: z.string().uuid().optional().describe("Filter by ai_agent_uuid."),
      aiAgentMode: z.string().optional().describe("Filter by ai_agent_mode."),
      aiEngagementStatusUuid: z.string().uuid().optional().describe("Filter by ai_engagement_status_uuid."),
      pipelineStageUuid: z.string().uuid().optional().describe("Filter by pipeline_stage_uuid."),
      companyUuid: z.string().uuid().optional().describe("Filter by company_uuid."),
      name: z.string().optional().describe("Filter by name."),
      firstName: z.string().optional().describe("Filter by first_name."),
      lastName: z.string().optional().describe("Filter by last_name."),
      companyName: z.string().optional().describe("Filter by company_name."),
      companyLnId: z.string().optional().describe("Filter by company_ln_id."),
      position: z.string().optional().describe("Filter by position."),
      headline: z.string().optional().describe("Filter by headline."),
      about: z.string().optional().describe("Filter by about."),
      avatarUrl: z.string().optional().describe("Filter by avatar_url."),
      lnMemberId: z.number().optional().describe("Filter by ln_member_id."),
      lnId: z.string().optional().describe("Filter by ln_id."),
      snId: z.string().optional().describe("Filter by sn_id."),
      linkedin: z.string().optional().describe("Filter by linkedin URL."),
      facebook: z.string().optional().describe("Filter by facebook."),
      twitter: z.string().optional().describe("Filter by twitter."),
      workEmail: z.string().optional().describe("Filter by work_email."),
      workEmailDomain: z.string().optional().describe("Filter by work_email_domain."),
      personalEmail: z.string().optional().describe("Filter by personal_email."),
      workPhoneNumber: z.string().optional().describe("Filter by work_phone_number."),
      personalPhoneNumber: z.string().optional().describe("Filter by personal_phone_number."),
      connectionsNumber: z.string().optional().describe("Filter by connections_number."),
      followersNumber: z.string().optional().describe("Filter by followers_number."),
      primaryLanguage: z.string().optional().describe("Filter by primary_language."),
      hasOpenProfile: z.string().optional().describe("Filter by has_open_profile."),
      hasVerifiedProfile: z.string().optional().describe("Filter by has_verified_profile."),
      hasPremium: z.string().optional().describe("Filter by has_premium."),
      rawAddress: z.string().optional().describe("Filter by raw_address."),
      location: z.string().optional().describe("Filter by location."),
      status: z.string().optional().describe("Filter by status."),
      linkedinStatus: z.string().optional().describe("Filter by linkedin_status."),
      emailStatus: z.string().optional().describe("Filter by email_status."),
      lastAutomationApproveAt: z.string().optional().describe("Filter by last_automation_approve_at."),
      lastStopOnReplyAt: z.string().optional().describe("Filter by last_stop_on_reply_at."),
      lastEnrichAtAfter: z.string().optional().describe("last_enrich_at after (ISO 8601)."),
      lastEnrichAtBefore: z.string().optional().describe("last_enrich_at before (ISO 8601)."),
      createdAfter: z.string().optional().describe("Created after (ISO 8601)."),
      createdBefore: z.string().optional().describe("Created before (ISO 8601)."),
      updatedAfter: z.string().optional().describe("Updated after (ISO 8601)."),
      updatedBefore: z.string().optional().describe("Updated before (ISO 8601)."),
      limit: z.number().min(1).max(1000).optional().describe("Max records (default 100, max 1000)."),
      offset: z.number().min(0).optional().describe("Skip N records (default 0)."),
      orderBy: z.string().optional().describe("Sort column (default created_at)."),
      order: z.enum(["asc", "desc"]).optional().describe("Sort order (default desc)."),
    },
    async (args) => {
      const client = getSupabase();
      if (!client) {
        return {
          content: [{ type: "text" as const, text: "Supabase not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_ANON_KEY) in .env." }],
          isError: true,
        };
      }
      const result = await getContacts(client, {
        uuid: args.uuid,
        teamId: args.teamId,
        userId: args.userId,
        listUuid: args.listUuid,
        dataSourceUuid: args.dataSourceUuid,
        aiAgentUuid: args.aiAgentUuid,
        aiAgentMode: args.aiAgentMode,
        aiEngagementStatusUuid: args.aiEngagementStatusUuid,
        pipelineStageUuid: args.pipelineStageUuid,
        companyUuid: args.companyUuid,
        name: args.name,
        firstName: args.firstName,
        lastName: args.lastName,
        companyName: args.companyName,
        companyLnId: args.companyLnId,
        position: args.position,
        headline: args.headline,
        about: args.about,
        avatarUrl: args.avatarUrl,
        lnMemberId: args.lnMemberId,
        lnId: args.lnId,
        snId: args.snId,
        linkedin: args.linkedin,
        facebook: args.facebook,
        twitter: args.twitter,
        workEmail: args.workEmail,
        workEmailDomain: args.workEmailDomain,
        personalEmail: args.personalEmail,
        workPhoneNumber: args.workPhoneNumber,
        personalPhoneNumber: args.personalPhoneNumber,
        connectionsNumber: args.connectionsNumber,
        followersNumber: args.followersNumber,
        primaryLanguage: args.primaryLanguage,
        hasOpenProfile: args.hasOpenProfile,
        hasVerifiedProfile: args.hasVerifiedProfile,
        hasPremium: args.hasPremium,
        rawAddress: args.rawAddress,
        location: args.location,
        status: args.status,
        linkedinStatus: args.linkedinStatus,
        emailStatus: args.emailStatus,
        lastAutomationApproveAt: args.lastAutomationApproveAt,
        lastStopOnReplyAt: args.lastStopOnReplyAt,
        lastEnrichAtAfter: args.lastEnrichAtAfter,
        lastEnrichAtBefore: args.lastEnrichAtBefore,
        createdAfter: args.createdAfter,
        createdBefore: args.createdBefore,
        updatedAfter: args.updatedAfter,
        updatedBefore: args.updatedBefore,
        limit: args.limit,
        offset: args.offset,
        orderBy: args.orderBy,
        order: args.order,
      });
      if (result.error) {
        return {
          content: [{ type: "text" as const, text: result.error }],
          isError: true,
        };
      }
      return {
        content: [{ type: "text" as const, text: JSON.stringify({ contacts: result.data, count: result.data.length }, null, 2) }],
      };
    }
  );
}
